---
editor_options:
  markdown:
    wrap: 72
---

# MGT 6203 Group Project Proposal Template

Please edit the following template to record your responses and provide
details on your project plan.

TEAM INFORMATION (1 point) Team #: 15 Team Members:

1.  Michael Munson (GT Id: mmunson34). I currently work as a product
    development engineer for a company in Minnesota. My educational
    background includes: Physics (BS), Mathematics (BA), Teaching (MAT);
    I am working on my Certificate in Data Science for the Chemical
    Industries. Previous projects include: effects of neural network
    formulation and OMLT implementation upon optimization case-study
    problems and ionic solution regression based on IR and Raman
    spectrum data processed through OLS, PLS, Ridge Regression and SVM.

2.  Matthew Rosenthal (GT Id: mrosenthal36). I'm a Technology Analyst
    for Southwest Airlines in Dallas, TX. In my current role I work to
    standardize and digitize workforce management processes for our
    airport employees. I have a BS in Industrial & Systems Engineering
    from the University of Florida with a Minor in Statistics (2019). I
    have worked on numerous analytics projects in my current role,
    undergrad studies, and previous ISE internships at Southwest and
    Disney.

3.  Jeffrey Sumner (GT Id: jsumner32). I'm a Data Engineer for Southern
    Star Central Gas Pipeline. My background is in Econ, Mathematics and
    Statistics. At Southern Star we have ranged from proof-of-concepts
    to full-fledged data science projects. Some of the things we have
    work on are forecasting revenue, predict whether we are operating
    outside of recommended bounds, performing text analytics on survey
    data, etc. In my spare time, I am the lead data scientist for a
    website that analyzes player tendencies and models win/loss
    probability for a handful of Indie games.

4.  Matthew Royalty (GT Id: mroyalty3). I'm a Data Engineer for Southern
    Star Central Gas Pipeline. I've been in this role for about 5 years
    developing data models and building ETL pipelines for our data
    warehouse initiative. I've, also, helped develop our initial revenue
    forecast. Prior to that, I spent 15 years as a lead software
    engineer working on a customer facing .Net application. I have a BS
    in Computer Science.

# OBJECTIVE/PROBLEM (5 points) Project Title: Background Information on chosen project topic:

**March Madness**

For many years, sports have not only been a staple of the entertainment
business, but also the subject of many analytic techniques. One of the
largest annual sporting events in the US is the NCAA March Madness
tournament. According to deadline.com, total television viewership
across the tournament's 67 games was 10.7 million viewers. Total game
attendance during the tournament was approximately 685,000 spectators
averaging 19,000 per session. Along with big-time viewership, comes
big-time revenue. Last year, it was estimated that the total revenue
created for the NCAA was \$1.15 billion not to mention other,
non-tracked revenue opportunities such as sports wagering. According to
investopia.com, \$3.1 billion was wagered during the 2022 NCAA
tournament.

Predicting the outcome of the Men's Division I March Madness Tournament
has been considered somewhat a "holy grail" for analytics enthusiasts.
How do you predict the outcome of 67 games that are played over three
weeks with any certainty? Especially considering potentially having to
forecast team upsets, player injuries, ... shifting data.

There are many different analyses that go into predicting outcomes of
the match ups. "Live win probabilities" can be calculated on a
play-by-play time frame; often incorporating factors such as: time
remaining in the game, score difference, pre-game win probabilities,
which team has possession, etc. There is also the "excitement index"
which indicates the rate of change of a team's chance of winning over
the course of the game. Exciting games can come with boosted viewership.
There are also "Elo ratings" which generally rate a team's chances of
winning games based on factors like: the location of the game, the
team's conference, the type of game (tournament or regular season), etc.
There are also many parallels to Elo, including Dr. Joel Sokol's LRMC
ratings (found at: <https://www2.isye.gatech.edu/~jsokol/lrmc/>).
[<https://fivethirtyeight.com/features/how-fivethirtyeight-is-forecasting-the-2016-ncaa-tournament/>]

## Problem Statement (clear and concise statement explaining purpose of your analysis and investigation):

The goal of our project is to create machine learning models that
reliably predicts the attendance at NCAA tournament games and outcome of
games given different match ups between teams, other pre-game
characteristics and player statistics.

## State your Primary Research Question (RQ):

Can we predict game attendance and outcome based on pre-game statistics?
At what level of accuracy can we predict the outcome of games with the
data that is currently available?

## Add some possible Supporting Research Questions (2-4 RQs that support problem statement):

1.  What is the relationship between team rankings (Massey Ordinal, Elo,
    AP Polls, Net Ranking, Coaches Poll, etc.) and attendance?

2.  What is the relationship between relative team rankings and
    likeliness to win?

## Business Justification: (Why is this problem interesting to solve from a business viewpoint? Try to quantify the financial, marketing or operational aspects and implications of this problem, as if you were running a company, non-profit organization, city or government that is encountering this problem.)

**Attendance:**\
Consumer-facing companies with any ad-merch budget are always looking
for the most efficient ways of converting people into loyal brand users.
The first part of this conversion is brand exposure, where a person
becomes aware of the brand's products. March Madness offers companies
multiple large-exposure events (tournament games and related content).
However, not all games will have the same level of exposure (in this
case, game attendance is the proxy for exposure). Predicting the
attendance of games beforehand will help companies choose the best
placement for their advertisements that will maximize their potential
conversion rates.

**Win / Loss Predictions:**\
In addition to advertisers, March Madness is also a huge opportunity for
betting companies. According to Fortune.com, approximately \$3.1 billion
was bet during the 2022 NCAA tournament. With each bet made, firms like
DraftKings and FanDuel take a cut, in addition to revenue from each ad
posted on their websites and apps. Although attendance predictions are
likely not of much value, a reliable game prediction model definitely
is. Being able to accurately predict tournament games can help betting
companies refine their lines and parlays, increase the monetary amount
of bets made, and maximize their revenue.

## DATASET/PLAN FOR DATA (4 points) Data Sources (links, attachments, etc.):

We plan to start our analysis with several major datasets.

-   We will use the ncaahoopR R package to gather box-score statistics,
    play-by-play data, win probabilities and more. The package can be
    found at the link listed below as well as generated data exports.

    -   <https://github.com/lbenz730/ncaahoopR>

    -   <https://github.com/lbenz730/ncaahoopR_data>

-   Much historical game data can be found from the NCAA website
    directly. This includes team records, team rankings per week ,
    conference standings, attendance records and more

    -   <https://www.ncaa.org/sports/2013/11/27/ncaa-men-s-basketball-records-books.aspx>

-   We also plan to use data from a long-running March Madness Kaggle
    competition, "Men's March Mania". This set contains 40 data files,
    with full regular season and tournament game scores dating back to
    the 1984-85 season. Historical datasets regarding game locations,
    conference affiliations, and coaching records are also included.

    -   <https://www.kaggle.com/competitions/mens-march-mania-2022/data>

-   An additional resource that could be used to capture already feature
    engineer characters like efficiency ratings can be found within
    these datasets from another kaggle resource

    -   <https://www.kaggle.com/datasets/andrewsundberg/college-basketball-dataset>

## Data Description (describe each of your data sources, include screenshots of a few rows of data):

-   NCAA Men's Basketball Data: - Records from 2000, including game
    attendance, team records per season, week-by-week Associated Press
    Poll Records - These records are mostly in .pdf format

-   The Kaggle "Men's March Mania" datasets include: - Basic
    information: Team ID's and Names; Tournament seeds since 1984; final
    scores of all regular season, tournament games; etc. - Team Box
    Scores: game-by-game stats at a team level (free throws, rebounds,
    turnovers, etc.) - Geography: the city locations of all games since
    2009 - Public Rankings: Weekly team rankings from multiple metrics -
    Supplemental Information: Coaches, conference affiliations, bracket
    structure, etc.

## Key Variables: (which ones will be considered independent and dependent? Are you going to create new variables? What variables do you hypothesize beforehand to be most important?)

For predicting game attendance, team ranking (Elo, Massey Ordinal, AP
Polls, etc.), fan base size and game location (distance from team
origin) seem to be good independent variables to consider. Regarding the
distance from team origin, this data would have to be roughly estimated.

## APPROACH/METHODOLOGY (8 points) Planned Approach (In paragraph(s), describe the approach you will take and what are the models you will try to use? Mention any data transformations that would need to happen. How do you plan to compare your models? How do you plan to train and optimize your model hyper-parameters?))

**Data Exploration:**

Should we make a comment about this?

**Data Cleaning:**

-   Eliminate 2020, 2021 Attendance - For our attendance analysis, we
    intend to remove 2021 NCAA tournament game attendance data due to
    the capacity limits due to COVID restrictions.

-   Proximity to Home - We plan to calculate the distance between City
    of game and the participating schools' college campus location
    coordinates (latitude / longitude differential)

-   Momentum - We plan to create a predictor for winning / losing streak
    (or last 5 or 10 games)

-   Win Quality - If available in our data sets, we will utilize NCAA
    based quality of win statistic of quadrants ("Quad I, II, III, IV
    win / loss"). If not available, we will create a version of this
    with our own formula utilizing point differential \* (Home or away)

-   Stat Differential - Possibly with player stats, Team game results -
    Tournament_Stage

**Types of Models:**

GLM: Attendance = Team_Fan_Base + Game_Excitement + Proximity_to_Home +
Momentum + Current_Record + Capacity_of_Site + Tournament_Stage

or % Attendance

Logistic: Probability to Win = Team_Rating (Team Rating differential) +
Proximity_to_Home + Momentum + Win_Quality + Stat_differential +
Tournament_Stage

-   What rating / combination of ratings gives us the best prediction

For Fun Models (if time): - Random Forests / Tree Models - Number of
Trees - Branching / Trimming

How to build models: - Train / Test Split: Train on random full years?
Train on interval of years, test on 2016, definitely leave out 2020,
2021

How to compare models? - accuracy - linear regression -\> RMSE - ANOVA

Potential Hyper-parameters: - Number of factors used (linear / logistic
regression) - Stepwise Regression, linear - mse, logistic - cut-off -\>
accuracy - LASSO, elastic net, Ridge - PCR (\# PCs)

## Anticipated Conclusions/Hypothesis (what results do you expect, how will your approach lead you to determining the final conclusion of your analysis) Note: At the end of the project, you do not have to be correct or have acceptable accuracy, the purpose is to walk us through an analysis that gives the reader insight into the conclusion regarding your objective/problem statement

**Attendance:**\
Multiple Linear Regression or equivalent(s) - We expect to figure out
the most effective factors in modeling attendance. Initially, we
anticipate the following to be important factors.

-   proximity to home (college campus)

-   conference strength

-   round of tournament will be the strongest factors that affect
    attendance Then also replicate attendance records to within an
    acceptable margin. Reflect on this season's results.

**Win / Loss Predictions:**\
Utilizing Logistic Regression or equivalent, we are aiming for accuracy
equal to or better than ESPN predictions. We expect that the most
effective factors in modeling win / loss are the following.

-   team ranking differential

-   win quality

-   proximity of game to hometown

-   team efficiency (offensive points per 100 possessions and points
    allowed per 100 possessions)

## What business decisions will be impacted by the results of your analysis? What could be some benefits?

**Attendance:**\
From the analysis, we hope to be an influential factor when considering
advertisement placements. Predicted attendance of games can be used to
calculate exposure to advertisements and be used by businesses to
maximize their advertising placements.

Accurate attendance predictions could be of benefit for initial and
secondary ticket markets for more capturing additional revenue with
demand based ticket pricing.

**Win / Loss Predictions:**\
As mentioned in the Business Justification, accurate tournament game
prediction models can help betting companies post better over/unders,
opening lines, and other forms of bets. Understanding what factors
influence a game's outcome can also help them refine their in-game
betting. If they can predict how the remainder of the game will go
(win/loss, specific stats, etc.), they can create bets that gamblers
actually want to wager on. All-in-all, offering more lucrative bets will
help drive users to the betting site and generate revenue.

## PROJECT TIMELINE/PLANNING (2 points) Project Timeline/Mention key dates you hope to achieve certain milestones by:

-   March 24: Data Prep procedures completed

-   April 2: Group Project: Presentation video and progress report (as
    stated in syllabus)

-   April 7: Models fully functional on datasets

-   April 14: Model validation and comparisons completed

-   April 16: Group Project: final paper, code and slides (as stated in
    syllabus)

-   April 19: Group Project: final video (as stated in syllabus)

## Appendix (any preliminary figures or charts that you would like to include):
